name: Deploy Server

on:
    push:
        branches: [test]

jobs:
    deploy:
        runs-on: host
        defaults:
            run:
                working-directory: ${{ secrets.WORKING_DIRECTORY }}
        steps:
            - name: Checkout repo # 불러오기
              run: |
                  git fetch --all
                  git checkout test

            - name: Set environmental variables # 환경변수 설정
              run: echo "${{ secrets.ENV_PRODUCTION }}" > .env

            - name: Deploy on Docker Compose container # Docker Compose 배포
              run: docker compose up -d

            - name: Test - make file
              run: echo "hello world" > hello-world
