name: Deploy container image

on:
    push:
        branches: [test]

jobs:
    deploy:
        runs-on: ubuntu-20.04

        steps:
            - name: Setting authentication keys
              run: |
                  mkdir -p ~/.ssh
                  echo "${{secrets.DEPLOYER_PUBLIC}}" > ~/.ssh/public
                  echo "${{secrets.DEPLOYER_PRIVATE}}" > ~/.ssh/private
                  chmod 600 ~/.ssh/private

            - name: Deploy with ssh
              run: |
                  ssh-keyscan -H ${{secrets.SERVER_IP}} >> ~/.ssh/known_hosts
                  ssh -T -i ~/.ssh/private deployer@${{secrets.SERVER_IP}} << EOF
                  echo "Logging into DockerHub"
                  echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
                  echo "Pulling the latest image"
                  docker pull seo/gitea-actions-dev
                  echo "Running the image"
                  docker run -d seo/gitea-actions-dev
                  EOF
